config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[new create]
  end
  #  edit update destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORIES = %w[chinese italian japanese french belgian]

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1 class="text-center"><%= @restaurants.name %></h1>
<div class="container">
  <div class="row">
    <div class="col-3">
      <ul>
        <% @restaurants.each do |restaurant| %>
          <li>
            <p>Name: <%= restaurant.name %></p>
            <p>Address: <%= restaurant.address %></p>
            <p>Phone: <%= restaurant.phone_number %></p>
            <p>Category: <%= restaurant.category %></p>
            <%= link_to 'Show', restaurant %>
          </li>
        <% end %>
          <%= link_to 'Insert a New restaurant', new_restaurant_path  %>
      </ul>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New Restaurant</h1>
  <%= simple_form_for(@restaurant) do |f| %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: Restaurant::CATEGORIES %>
    </div>
    <div class="form-actions">
      <%= f.submit class: "btn btn-primary"%>
    </div>
  <% end %>

  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name.capitalize %></h1>

  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>

  <p>
    <strong>Phone Number:</strong>
    <%= @restaurant.phone_number %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @restaurant.category %>
  </p>

  <div>
    <% @restaurant.reviews.each do |review| %>
      <div class="d-flex">
        <p class="mr-3">Rating:<%= review.rating %>|</p>
        <p>Content:<%= review.content %> </p>
      </div>
    <% end %>
  </div>
  <h5>Send your Review</h5>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating, collection: 0..5 %>
    <%= f.input :content %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

  <%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %> |
  <%= link_to 'Back', restaurants_path %>
</div>